// <auto-generated />
namespace OFRPDMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class march13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(march13));
        
        string IMigrationMetadata.Id
        {
            get { return "201303130632433_march13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
