//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterReferral
    {
        public CenterReferral()
        {
            this.Referrals = new HashSet<Referral>();
        }
    
        public int Id { get; set; }
        public int CenterId { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<Referral> Referrals { get; set; }
        public virtual Center Center { get; set; }
    }
}
