//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public Child()
        {
            this.EventParticipants = new HashSet<EventParticipant>();
        }
    
        public int Id { get; set; }

        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public System.DateTime Birthdate { get; set; }
        public int PrimaryGuardianId { get; set; }
    
        public virtual PrimaryGuardian PrimaryGuardian { get; set; }
        public virtual ICollection<EventParticipant> EventParticipants { get; set; }
    }
}
