//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventParticipant
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public string ParticipantType { get; set; }
        public Nullable<int> SpecialEventId { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> PrimaryGuardianId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> SecondaryGuardianId { get; set; }
    
        public virtual SpecialEvent SpecialEvent { get; set; }
        public virtual Event Event { get; set; }
        public virtual PrimaryGuardian PrimaryGuardian { get; set; }
        public virtual Child Child { get; set; }
        public virtual SecondaryGuardian SecondaryGuardian { get; set; }
    }
}
