//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeResource
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Marker { get; set; }
        public string Language { get; set; }
        public int CenterFreeResourceId { get; set; }
    
        public virtual CenterFreeResource CenterFreeResource { get; set; }
    }
}
