//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GivenResource
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateGiven { get; set; }
        public int Count { get; set; }
        public int CenterId { get; set; }
    
        public virtual Center Center { get; set; }

        // required because of 1 to 1 relationship with CenterFreeResource
        [Required]
        public virtual CenterFreeResource CenterFreeResource { get; set; }
    }
}
