//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PrimaryGuardianBorrow> PrimaryGuardianBorrows { get; set; }
        public DbSet<PrimaryGuardian> PrimaryGuardians { get; set; }
        public DbSet<SecondaryGuardian> SecondaryGuardians { get; set; }
        public DbSet<EventParticipant> EventParticipants { get; set; }
        public DbSet<Child> Children { get; set; }
        public DbSet<Allergy> Allergies { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Center> Centers { get; set; }
        public DbSet<CenterReferral> CenterReferrals { get; set; }
        public DbSet<Referral> Referrals { get; set; }
        public DbSet<CenterAccount> CenterAccounts { get; set; }
        public DbSet<Account> Accounts { get; set; }
        public DbSet<CenterFreeResource> CenterFreeResources { get; set; }
        public DbSet<SpecialEvent> SpecialEvents { get; set; }
        public DbSet<LibraryItem> LibraryItems { get; set; }
        public DbSet<LibraryResource> LibraryResources { get; set; }
        public DbSet<GivenResource> GivenResources { get; set; }
    }
}
