//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryGuardianBorrow
    {
        public PrimaryGuardianBorrow()
        {
            this.BorrowableItems = new HashSet<BorrowableItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime BorrowedDate { get; set; }
        public int PrimaryGuardianId { get; set; }
    
        public virtual ICollection<BorrowableItem> BorrowableItems { get; set; }
        public virtual PrimaryGuardian PrimaryGuardian { get; set; }
    }
}
