//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryGuardian
    {
        public PrimaryGuardian()
        {
            this.EventParticipants = new HashSet<EventParticipant>();
            this.Children = new HashSet<Child>();
            this.Allergies = new HashSet<Allergy>();
            this.SecondaryGuardians = new HashSet<SecondaryGuardian>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string PostalCodePrefix { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public int CenterId { get; set; }
    
        public virtual ICollection<EventParticipant> EventParticipants { get; set; }
        public virtual ICollection<Child> Children { get; set; }
        public virtual ICollection<Allergy> Allergies { get; set; }
        public virtual ICollection<SecondaryGuardian> SecondaryGuardians { get; set; }
        public virtual Center Center { get; set; }
    }
}
