//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryGuardianBorrow
    {
        public int Id { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public int PrimaryGuardianId { get; set; }
        public bool Returned { get; set; }
        public int LibraryItemId { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual PrimaryGuardian PrimaryGuardian { get; set; }
        public virtual LibraryItem LibraryItem { get; set; }
    }
}
