//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFRPDMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SecondaryGuardian
    {
        [Key, ForeignKey("PrimaryGuardian")]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RelationshipToChild { get; set; }
        public Nullable<int> Phone { get; set; }
    
        public virtual PrimaryGuardian PrimaryGuardian { get; set; }
    }
}
